import type { HeroCard } from '@/engine/types';

// Hero stats from the original TcgEngine spec.
// Cards marked TODO_STAT have unknown values and should be tuned against the original .asset files.
export const TODO_STAT = -1;

export const HEROES: HeroCard[] = [
  {
    id: 'hero_abrams',
    name: 'Abrams',
    type: 'hero',
    rarity: 3,
    atk: 3,
    hp: 14,
    skill: 'skill_abrams',
    passives: ['passive_abrams_heal'],
    ult: 'ult_abrams',
    text: 'Tank. Heal 2 if Active at start of turn. Skill: 2 spirit dmg + Stun 2.',
  },
  {
    id: 'hero_dynamo',
    name: 'Dynamo',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 11,
    skill: 'skill_dynamo',
    passives: ['passive_dynamo_heal'],
    ult: 'ult_dynamo',
    text: 'Healer. End of turn heal all allies 1. Skill: Heal ally 3.',
  },
  {
    id: 'hero_haze',
    name: 'Haze',
    type: 'hero',
    rarity: 3,
    atk: 4,
    hp: 8,
    skill: 'skill_haze',
    passives: ['passive_haze_stunbonus'],
    ult: 'ult_haze',
    text: '+2 ATK vs Stunned. Skill: 2 dmg + Stun 2.',
  },
  {
    id: 'hero_kelvin',
    name: 'Kelvin',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 12,
    skill: 'skill_kelvin',
    passives: ['passive_kelvin_chill'],
    ult: 'ult_kelvin',
    text: 'Aura: enemy Active -1 ATK. Skill: 2 dmg.',
  },
  {
    id: 'hero_lady_geist',
    name: 'Lady Geist',
    type: 'hero',
    rarity: 3,
    atk: 3,
    hp: 9,
    skill: 'skill_lady_geist',
    ult: 'ult_lady_geist',
    text: 'Spirit caster who pays in blood. Skill: 3 spirit dmg.',
  },
  {
    id: 'hero_lash',
    name: 'Lash',
    type: 'hero',
    rarity: 3,
    atk: 4,
    hp: 8,
    skill: 'skill_lash',
    passives: ['passive_lash_swap'],
    ult: 'ult_lash',
    text: '+2 ATK on first attack after swap. Skill: 3 dmg.',
  },
  {
    id: 'hero_mo_krill',
    name: 'Mo & Krill',
    type: 'hero',
    rarity: 3,
    atk: 3,
    hp: 11,
    skill: 'skill_mo_krill',
    ult: 'ult_mo_krill',
    text: 'Tunneling duo. Skill: 2 dmg + heal self 1.',
  },
  {
    id: 'hero_paige',
    name: 'Paige',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 10,
    skill: 'skill_paige',
    ult: 'ult_paige',
    text: 'Healer. Skill: Shield(3) on ally.',
  },
  {
    id: 'hero_rem',
    name: 'Rem',
    type: 'hero',
    rarity: 3,
    atk: 1,
    hp: 7,
    skill: 'skill_rem',
    passives: ['passive_rem_benchheal'],
    ult: 'ult_rem',
    text: 'Bench-only. Start of turn heal Active ally 2. Skill: Heal 3.',
    flags: { benchOnly: true },
  },
  {
    id: 'hero_seven',
    name: 'Seven',
    type: 'hero',
    rarity: 3,
    atk: 3,
    hp: 9,
    skill: 'skill_seven',
    passives: ['passive_seven_zap'],
    ult: 'ult_seven',
    text: 'End of turn 1 spirit to random enemy Bench. Skill: 3 dmg.',
  },
  {
    id: 'hero_shiv',
    name: 'Shiv',
    type: 'hero',
    rarity: 3,
    atk: 4,
    hp: 9,
    skill: 'skill_shiv',
    ult: 'ult_shiv',
    text: 'Bleeds anything that touches him. Skill: Bleed 2 (3 turns).',
  },
  {
    id: 'hero_sinclair',
    name: 'Sinclair',
    type: 'hero',
    rarity: 3,
    atk: 3,
    hp: 10,
    skill: 'skill_sinclair',
    ult: 'ult_sinclair',
    text: 'Tactician with a smile. Skill: ally +2 Spirit Power for 2 turns.',
  },
  {
    id: 'hero_vindicta',
    name: 'Vindicta',
    type: 'hero',
    rarity: 3,
    atk: 4,
    hp: 7,
    skill: 'skill_vindicta',
    ult: 'ult_vindicta',
    text: 'Long Range. Skill: 2 dmg + Sleep 2.',
    flags: { longRange: true },
  },
  {
    id: 'hero_viscous',
    name: 'Viscous',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 13,
    skill: 'skill_viscous',
    ult: 'ult_viscous',
    text: 'A wall of green slime. Skill: gain Invincibility 1.',
  },
  {
    id: 'hero_yamato',
    name: 'Yamato',
    type: 'hero',
    rarity: 3,
    atk: 4,
    hp: 9,
    skill: 'skill_yamato',
    ult: 'ult_yamato',
    text: 'Twin blades, Shadow path. Skill: 3 spirit dmg.',
  },
];

export const HEROES_BY_ID = Object.fromEntries(HEROES.map((h) => [h.id, h])) as Record<string, HeroCard>;
