import type { HeroCard } from '@/engine/types';

/**
 * 19 heroes total. Each hero has EXACTLY ONE distinguishing mechanic — either a
 * `skill` (Activate trigger, costs the player's one-skill-per-turn) OR an entry
 * in `passives` (always-on or trigger-based, no cast). Never both.
 *
 * Split (9 passive / 10 skill):
 *   PASSIVE: Abrams, Drifter, Haze, Mirage, Mo & Krill, Rem, Shiv, Vindicta, Wraith
 *   SKILL:   Dynamo, Kelvin, Lady Geist, Lash, Paige, Seven, Sinclair, Viscous, Warden, Yamato
 *
 * Archetypes (8 roles): tank, marksman, caster, healer, bruiser, disruptor,
 * trickster, assassin. Ultimates are 1:1 with heroes.
 *
 * Card text format: `abilityName` carries the skill/passive name (rendered as a
 * tag next to the role on the card subtitle). `text` carries ONLY the
 * mechanical effect — no "Role. AbilityName:" prefix.
 */
export const HEROES: HeroCard[] = [
  // ----- PASSIVE-only heroes -----
  {
    id: 'hero_abrams',
    name: 'Abrams',
    type: 'hero',
    rarity: 3,
    atk: 1,
    hp: 6,
    passives: ['passive_abrams_heal'],
    ult: 'ult_abrams',
    abilityName: 'Infernal Resilience',
    text: 'Heals 2 at start of own turn while Active.',
  },
  {
    id: 'hero_haze',
    name: 'Haze',
    type: 'hero',
    rarity: 3,
    atk: 3,
    hp: 4,
    passives: ['passive_haze_stunbonus'],
    ult: 'ult_haze',
    abilityName: 'Fixation',
    text: '+2 ATK vs Stunned targets.',
  },
  {
    id: 'hero_mo_krill',
    name: 'Mo & Krill',
    type: 'hero',
    rarity: 3,
    atk: 1,
    hp: 6,
    passives: ['passive_mo_krill_burrow'],
    ult: 'ult_mo_krill',
    abilityName: 'Burrow',
    text: 'Cleanses all debuffs from self at start of own turn.',
  },
  {
    id: 'hero_rem',
    name: 'Rem',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 4,
    passives: ['passive_rem_benchheal'],
    ult: 'ult_rem',
    abilityName: 'Lil Helpers',
    text: 'Bench-only. Start of own turn: heals ally Active 2.',
    flags: { benchOnly: true },
  },
  {
    id: 'hero_shiv',
    name: 'Shiv',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 6,
    passives: ['passive_shiv_bleed'],
    ult: 'ult_shiv',
    abilityName: 'Serrated Knives',
    text: 'Attacks apply Bleed 1 for 2 turns.',
  },
  {
    id: 'hero_vindicta',
    name: 'Vindicta',
    type: 'hero',
    rarity: 3,
    atk: 3,
    hp: 4,
    passives: ['passive_vindicta_flight'],
    ult: 'ult_vindicta',
    abilityName: 'Flight',
    text: 'Takes 1 less bullet damage from all sources.',
  },
  {
    id: 'hero_wraith',
    name: 'Wraith',
    type: 'hero',
    rarity: 3,
    atk: 3,
    hp: 4,
    passives: ['passive_wraith_mixed'],
    ult: 'ult_wraith',
    abilityName: 'Mixed Bullets',
    text: 'Attacks split half bullet / half spirit — pierces single-type resists.',
  },

  // ----- SKILL-only heroes -----
  {
    id: 'hero_dynamo',
    name: 'Dynamo',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 6,
    skill: 'skill_dynamo',
    ult: 'ult_dynamo',
    abilityName: 'Rejuvenating Aurora',
    text: 'Heals an ally for 2 (+ caster Spirit).',
  },
  {
    id: 'hero_kelvin',
    name: 'Kelvin',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 4,
    skill: 'skill_kelvin',
    ult: 'ult_kelvin',
    abilityName: 'Frost Grenade',
    text: '2 spirit dmg to enemy Active + heal ally Active 2.',
  },
  {
    id: 'hero_lady_geist',
    name: 'Lady Geist',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 4,
    skill: 'skill_lady_geist',
    ult: 'ult_lady_geist',
    abilityName: 'Essence Bomb',
    text: '4 spirit dmg to any enemy.',
  },
  {
    id: 'hero_lash',
    name: 'Lash',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 4,
    skill: 'skill_lash',
    ult: 'ult_lash',
    abilityName: 'Ground Strike',
    text: '2 spirit dmg + Stun 1 turn.',
  },
  {
    id: 'hero_paige',
    name: 'Paige',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 4,
    skill: 'skill_paige',
    ult: 'ult_paige',
    abilityName: 'Plot Armor',
    text: 'Shield 4 on an ally.',
  },
  {
    id: 'hero_seven',
    name: 'Seven',
    type: 'hero',
    rarity: 3,
    atk: 3,
    hp: 4,
    skill: 'skill_seven_static',
    ult: 'ult_seven',
    abilityName: 'Static Charge',
    text: '1 spirit dmg + Charged 2 — Stun 1 turn on expiry.',
  },
  {
    id: 'hero_sinclair',
    name: 'Sinclair',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 4,
    skill: 'skill_sinclair',
    ult: 'ult_sinclair',
    abilityName: 'Vexing Bolt',
    text: '3 spirit dmg to any enemy.',
  },
  {
    id: 'hero_viscous',
    name: 'Viscous',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 6,
    skill: 'skill_viscous',
    ult: 'ult_viscous',
    abilityName: 'The Cube',
    text: 'Gain Unstoppable 1 + heal 1.',
  },
  {
    id: 'hero_yamato',
    name: 'Yamato',
    type: 'hero',
    rarity: 3,
    atk: 2,
    hp: 6,
    skill: 'skill_yamato',
    ult: 'ult_yamato',
    abilityName: 'Power Slash',
    text: '2 spirit dmg to any enemy.',
  },
  {
    id: 'hero_warden',
    name: 'Warden',
    type: 'hero',
    rarity: 3,
    atk: 3,
    hp: 4,
    skill: 'skill_warden',
    ult: 'ult_warden',
    abilityName: 'Willpower',
    text: 'Shield 2 on self (+ caster Spirit).',
  },
  {
    id: 'hero_mirage',
    name: 'Mirage',
    type: 'hero',
    rarity: 3,
    atk: 1,
    hp: 3,
    passives: ['passive_mirage_djinns_mark'],
    ult: 'ult_mirage',
    abilityName: "Djinn's Mark",
    text: "Attacks apply 1 stack of Djinn's Mark (max 4) for 3 turns. Mark detonates at max stacks or on expiry for 2 spirit dmg per stack.",
  },
  {
    id: 'hero_drifter',
    name: 'Drifter',
    type: 'hero',
    rarity: 3,
    atk: 3,
    hp: 4,
    passives: ['passive_drifter_bloodscent'],
    ult: 'ult_drifter',
    abilityName: 'Bloodscent',
    text: 'Heal 1 on attack. +3 bullet dmg vs targets at 4 HP or below.',
  },
];

export const HEROES_BY_ID = Object.fromEntries(HEROES.map((h) => [h.id, h])) as Record<string, HeroCard>;
